apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 8080         # הפורט דרך הסרוויס
      targetPort: 80     # הפורט בתוך הקונטיינר
  type: NodePort

